version: "2"
services:
  analytics-training:
    build:
      context: .
      dockerfile: Dockerfile.analytics-training
    image: analytics-training:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      GREMLIN_USE_SECURE_CONNECTION: "false"
      BAYESIAN_GREMLIN_HTTP_SERVICE_HOST: "localhost"
      BAYESIAN_GREMLIN_HTTP_SERVICE_PORT: "8181"
      BAYESIAN_GREMLIN_WS_SERVICE_HOST: "localhost"
      BAYESIAN_GREMLIN_WS_SERVICE_PORT: "8182"
      AWS_S3_ACCESS_KEY_ID: ""
      AWS_S3_SECRET_ACCESS_KEY: ""
      AWS_BUCKET: ""
      DEPLOYMENT_PREFIX: ""
